name: Create Arch Linux Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Makepkg
        run: |
          RELEASE_VERSION=v0.1.2
          # RELEASE_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
          sudo chmod 777 -R .
          cd .github/workflows/arch
          cp ./release-entrypoint.sh ./entrypoint.sh
          docker build -t archl .
          cd ../../../
          docker run -a stdin -a stdout -a stderr -e RELEASE_VERSION=$RELEASE_VERSION --mount type=bind,source=$(pwd),target=/splice archl
      -
        name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: splice-releases
          source_dir: archl-files
          destination_dir: splicectl/aur/
  test:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Test package
        run: |
          RELEASE_VERSION=v0.1.2
          # RELEASE_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
          sudo chmod 777 -R .
          cd .github/workflows/arch
          cp ./test-entrypoint.sh ./entrypoint.sh
          docker build -t archl .
          cd ../../../
          docker run -a stdin -a stdout -a stderr -e RELEASE_VERSION=$RELEASE_VERSION --mount type=bind,source=$(pwd),target=/splice archl
