name: Create Release

on:
  push:
    tags:
      - '*' # TODO

jobs:
  debianrelease:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0